### ISSUE TITLE
managed resource: empty secret with writeConnectionSecretToRef in the composition

### ISSUE THREAD

**Issue by lcoding4fun** [crossplane-contrib/provider-mongodbatlas#23]
Hello! I am running into challenges getting mongoDB connection strings into Kubernetes secrets. Is there something wrong with my configuration? Thank you in advance for any guidance! 

### Context
I have a composition pipeline that deploys a project and a cluster using this provider. The pipeline uses `function-patch-and-transform` steps to provision the project and cluster managed resources.
- for both the project and cluster resources, I configure `writeConnectionSecretToRef` , providing unique secret names and an existing namespace

```
              apiVersion: mongodbatlas.crossplane.io/v1alpha1
              kind: Project
              spec:
...
                providerConfigRef:
                  name: provider-mongodbatlas
                writeConnectionSecretToRef:
                  namespace: docs
                  name: secret1
...
        
              apiVersion: mongodbatlas.crossplane.io/v1alpha2
              kind: Cluster
...
                providerConfigRef:
                  name: provider-mongodbatlas
                writeConnectionSecretToRef:
                  namespace: docs
                  name: secret2
...
```

### Expected behaviour:
- the project, cluster and secrets are created
- after the resources are created, the secrets should be populated with all the sensitive fields of the managed resource. 
- the secrets should not be empty non-empty after the resources are created 

### Actual behaviour
- the secrets are created, but are empty, even after the project and cluster resources are created.
- I can query the cluster resource and see the connection strings (one for each shard in the Mongo Uri property), so I know that the data is available, but I can't seem to get those connection strings into Kubernetes secrets .

```
NAME      TYPE                                DATA   AGE
secret1   connection.crossplane.io/v1alpha1   0      5m10s
secret2   connection.crossplane.io/v1alpha1   0      4m57s
```

## Note
I also tried the scenario where I specify `writeConnectionSecretToRef` in the claim, along with a secret name and an existing namespace. Similarly, the secret is created but the secret contents are empty as well.
